export type OpeningLesson = {
  id: string;
  opening: string;
  variation: string;
  opponentMove: string;
  answer: string;
  side: "w" | "b";
  summary: string;
  keyIdea: string;
  line: string[];
  notes: string[];
};

export const OPENING_LESSONS: OpeningLesson[] = [
  {
    id: "london-classical",
    opening: "London System",
    variation: "Classical setup · as White",
    opponentMove: "Black plays ...Bd6",
    answer: "Trade with Bxd6, then stabilize with c3 and Nbd2.",
    side: "w",
    summary: "Build the London against Black's natural ...d5 and ...Bd6 setup.",
    keyIdea: "Meet ...Bd6 with Bxd6. Black recaptures with the queen, while you complete c3 and Nbd2.",
    line: [
      "d2d4", "d7d5", "g1f3", "g8f6", "c1f4", "e7e6", "e2e3", "f8d6",
      "f4d6", "d8d6", "c2c3", "e8g8", "b1d2",
    ],
    notes: [
      "Claim the center with d4.",
      "Black mirrors with ...d5.",
      "Nf3 supports d4 and keeps the f-pawn free.",
      "Black develops normally.",
      "Bf4 is the London bishop, developed outside the pawn chain.",
      "Black supports the center with ...e6.",
      "e3 opens your dark-squared bishop and reinforces d4.",
      "...Bd6 challenges your active bishop.",
      "Exchange bishops before Black can gain a tempo with ...Bxf4.",
      "Black's queen recaptures.",
      "c3 makes d4 harder to attack and prepares a stable center.",
      "Black castles.",
      "Nbd2 completes the core London setup.",
    ],
  },
  {
    id: "london-early-c5",
    opening: "London System",
    variation: "Early ...c5 · as White",
    opponentMove: "Black hits the center with ...c5",
    answer: "Play e3 and c3. Keep d4 supported before completing Nbd2.",
    side: "w",
    summary: "Black challenges d4 early. Build the London center before deciding whether to take on c5.",
    keyIdea: "c3 is the useful reply to ...c5: it reinforces d4 and keeps your central structure intact.",
    line: [
      "d2d4", "d7d5", "g1f3", "g8f6", "c1f4", "c7c5", "e2e3", "b8c6",
      "c2c3", "e7e6", "b1d2",
    ],
    notes: [
      "Claim the center with d4.",
      "Black takes space with ...d5.",
      "Nf3 supports d4.",
      "Black develops normally.",
      "Develop the London bishop before closing the c1-h6 diagonal.",
      "Black challenges d4 immediately with ...c5.",
      "e3 reinforces d4 and frees the dark-squared bishop.",
      "...Nc6 adds pressure to d4.",
      "c3 is the key response: it makes d4 durable.",
      "Black completes the central pawn chain.",
      "Nbd2 finishes the basic setup and prepares e4 when appropriate.",
    ],
  },
  {
    id: "london-fianchetto",
    opening: "London System",
    variation: "Kingside fianchetto · as White",
    opponentMove: "Black fianchettoes with ...g6 and ...Bg7",
    answer: "Use Be2 and O-O. Keep the center solid instead of forcing an early attack.",
    side: "w",
    summary: "Against a King's Indian-style setup, finish development and castle before choosing a pawn break.",
    keyIdea: "Black's bishop will pressure the center from g7. Your answer is calm development: Be2, O-O, then c3 or h3 as the position asks.",
    line: [
      "d2d4", "g8f6", "g1f3", "g7g6", "c1f4", "f8g7", "e2e3", "e8g8",
      "f1e2", "d7d6", "e1g1",
    ],
    notes: [
      "Take the center with d4.",
      "Black delays a central pawn commitment.",
      "Nf3 supports your center.",
      "...g6 signals a kingside fianchetto.",
      "Develop the London bishop before Black can contest it with ...e6.",
      "The g7 bishop now eyes the long diagonal.",
      "e3 keeps d4 protected.",
      "Black castles.",
      "Be2 is the quiet, useful development move.",
      "...d6 supports Black's e5 break.",
      "Castle before deciding how to expand.",
    ],
  },
  {
    id: "sicilian-najdorf",
    opening: "Sicilian Defense",
    variation: "Najdorf setup · as Black",
    opponentMove: "White chooses the Open Sicilian with Nf3 and d4",
    answer: "Meet it with ...d6, ...cxd4, ...Nf6, then the Najdorf ...a6 and ...e5.",
    side: "b",
    summary: "Reach the Najdorf with ...a6, then challenge White's center with ...e5.",
    keyIdea: "The moves ...a6 and ...e5 define the plan: control b5, then make White's d4-knight decide where it belongs.",
    line: [
      "e2e4", "c7c5", "g1f3", "d7d6", "d2d4", "c5d4", "f3d4", "g8f6",
      "b1c3", "a7a6", "c1e3", "e7e5",
    ],
    notes: [
      "White claims space with e4.",
      "...c5 is the Sicilian: fight for d4 from the side.",
      "White develops toward the center.",
      "...d6 reinforces e5 and prepares development.",
      "White challenges the center immediately.",
      "...cxd4 creates the characteristic open Sicilian position.",
      "White recaptures with the knight.",
      "...Nf6 attacks e4 and develops with tempo.",
      "White supports the center with Nc3.",
      "...a6 is the Najdorf move: take b5 away and prepare queenside play.",
      "Be3 is a common attacking setup.",
      "...e5 hits the knight on d4 and claims central space.",
    ],
  },
  {
    id: "sicilian-alapin",
    opening: "Sicilian Defense",
    variation: "Alapin · as Black",
    opponentMove: "White plays 2.c3",
    answer: "Challenge the center with ...Nf6; after e5, reroute with ...Nd5 and take on d4.",
    side: "b",
    summary: "The Alapin avoids the Open Sicilian. Let White advance, then challenge the center directly.",
    keyIdea: "...Nf6 attacks e4 immediately. After e5, ...Nd5 is a useful square, and ...cxd4 removes White's d4 pawn.",
    line: [
      "e2e4", "c7c5", "c2c3", "g8f6", "e4e5", "f6d5", "d2d4", "c5d4",
      "g1f3", "b8c6",
    ],
    notes: [
      "White claims e4.",
      "Start the Sicilian with ...c5.",
      "2.c3 announces the Alapin and supports d4.",
      "...Nf6 attacks the e4 pawn before White's center is complete.",
      "White pushes e5 to gain space.",
      "...Nd5 keeps the knight active and eyes c3 and e3.",
      "White builds the intended pawn center.",
      "...cxd4 removes one central pawn before it gets too strong.",
      "White develops toward the center.",
      "...Nc6 adds development and pressure to d4/e5.",
    ],
  },
  {
    id: "sicilian-closed",
    opening: "Sicilian Defense",
    variation: "Closed Sicilian · as Black",
    opponentMove: "White plays 2.Nc3 and 3.g3",
    answer: "Develop with ...Nc6 and ...g6; fianchetto, then support the center with ...d6.",
    side: "b",
    summary: "The Closed Sicilian is slower than the Open. Match White's kingside fianchetto and prepare your own counterplay.",
    keyIdea: "Against g3 and Bg2, ...Nc6, ...g6, ...Bg7, and ...d6 form a reliable setup before you choose ...e5 or queenside expansion.",
    line: [
      "e2e4", "c7c5", "b1c3", "b8c6", "g2g3", "g7g6", "f1g2", "f8g7",
      "d2d3", "d7d6",
    ],
    notes: [
      "White starts with e4.",
      "...c5 claims the Sicilian structure.",
      "Nc3 avoids the immediate Open Sicilian pawn break.",
      "...Nc6 develops and controls d4.",
      "g3 prepares a kingside fianchetto.",
      "...g6 mirrors the fianchetto setup.",
      "White's bishop reaches g2.",
      "...Bg7 completes your long-diagonal bishop.",
      "White keeps the center flexible with d3.",
      "...d6 supports your center and prepares development.",
    ],
  },
];
